global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: "orders-api"
    static_configs:
      - targets: ["orders-api:8080"]
    metrics_path: /metrics

  - job_name: "inventory-api"
    static_configs:
      - targets: ["inventory-api:8081"]
    metrics_path: /metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
